### ISSUE TITLE
Invalid MerchantId

### ISSUE THREAD

**Issue by mozgbrasil** [alexandreo/BrasPag#2]
Ola Bom dia

Acabo de criar uma conta em 

https://cadastrosandbox.braspag.com.br/

Ao informar o MerchantId no arquivo de exemplo AuthorizeTransaction.php

é exibido o retorno

```
stdClass Object
(
    [AuthorizeTransactionResult] => stdClass Object
        (
            [CorrelationId] => 27f3a2ac-4e91-11e6-8a46-3417eb8ad2b3
            [Success] => 
            [ErrorReportDataCollection] => stdClass Object
                (
                    [ErrorReportDataResponse] => stdClass Object
                        (
                            [ErrorCode] => 122
                            [ErrorMessage] => Invalid MerchantId
                        )

                )

        )

)
```

**Comment by alexandreo** [comment]
Bom dia, 

Para utilizar ambiente de homologação basta passar como exemplo abaixo.
$brasPag = new BrasPag(false);
Para utilizar ambiente de produção basta passar como exemplo abaixo.
$brasPag = new BrasPag(true);

caso seu MerchantId continue exibir á mensagem "invalid MerchantId" entrar em contato com a BrasPag.

**Comment by mozgbrasil** [comment]
Boa Tarde

Vejo que sua biblioteca faz acesso a ambiente diferente do informado na atual API

http://apidocs.braspag.com.br/

Sabe me dizer a diferença, creio que seja esse caso

**Comment by alexandreo** [comment]
Essa biblioteca é para o ambiente em SOAP da braspag, segue abaixo a documentação oficial da Braspag:

End Point: https://homologacao.pagador.com.br/webservice/pagadorTransaction.asmx
Documentação: http://www.braspag.com.br/site/wp-content/uploads/manuais/pagador-transaction-autorizacao-captura-cancelamento-e-estorno-v1.15.2.pdf

Com está api você pode utilizar os seguintes method: Autorização, Captura, Cancelamento e Estorno.
